modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="solmaid"
version="1.0.0"
displayName="Spice of Life: Maid"
authors="摸里傻"

description='''
女仆的生活也需要一些美食的调味
'''

[[mixins]]
config="solmaid.mixins.json"

[[dependencies."solmaid"]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies."solmaid"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."solmaid"]]
    modId="touhou_little_maid"
    type="required"
    versionRange="[1.4.6,)"
    ordering="NONE"
    side="BOTH"

